In [1]:
import pandas as pd
import numpy as np
print (" Environnement ␣ configure ␣ avec ␣ succes ␣!")
print ( f" Version ␣de␣ Pandas ␣:␣{pd. __version__ }")

 Environnement ␣ configure ␣ avec ␣ succes ␣!
 Version ␣de␣ Pandas ␣:␣3.0.0

In [9]:
import pandas as pd

df = pd.read_csv("../data/student_data.csv")

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [13]:

path="../data/student_data.csv"
df=pd.read_csv(path, sep=',')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [14]:
#3/.affichage des 5premiers lignes
print("apercu _des_donnees")
display(df.head())

apercu _des_donnees

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [12]:
#verification de structure
print("\ninformations_le_dataset")
df.info()

informations_le_dataset
<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                               --------------  -----
 0   school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3  395 non-null    str
dtypes: str(1)
memory usage: 3.2 KB

In [5]:
import pandas as pd

df_json = pd.read_json("../data/palestinian_movies.json")

df_json.head()

                                              movies
0  {'titleText': {'text': 'Curfew'}, 'id': 'tt010...
1  {'titleText': {'text': 'Hikayatul jawahiri tha...
2  {'titleText': {'text': 'Giraffada'}, 'id': 'tt...
3  {'titleText': {'text': 'Gaza mon amour'}, 'id'...
4  {'titleText': {'text': 'Farha'}, 'id': 'tt1155...

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:@localhost/etudiants")

query = "SELECT * FROM student_data.csv WHERE G3 > 15"

In [5]:
import requests
import pandas as pd
url= "https://jsonplaceholder.typicode.com/posts"
response=requests.get(url)
data=response.json()
df_api=pd.DataFrame(data)
df_api.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [ ]:
from bs4 import BeautifulSoup
url="https://books.toscrape.com"
response=requests.get(url)
soup=BeautifulSoup(response.text,"html.parser")
titles=[book.text for book in soup.find_all("h3")]
df_scraping=pd.DataFrame(titles,columns=["title"])
df_scraping.head()

                          title
0            A Light in the ...
1            Tipping the Velvet
2                    Soumission
3                 Sharp Objects
4  Sapiens: A Brief History ...